### ISSUE TITLE
Spring Boot cannot build a Java 17 native Docker image because native-image is failing to unresolved method

### ISSUE THREAD

**Issue by Nikolas-Charalambidis** [paketo-buildpacks/native-image#112]
## What happened?

I have a simple Spring Boot application using Java 17 and Maven with the following dependencies I would like to build using `spring-boot-maven-plugin` as a native Docker image. The parent version is `2.6.0`:
- `org.springframework.boot`:`spring-boot-starter-data-r2dbc`
- `org.springframework.boot`:`spring-boot-starter-webflux`
- `org.springframework.boot`:`spring-boot-starter-actuator`
- `org.springframework.experimental`:`spring-native` (from `org.springframework.experimental`)
- `io.r2dbc`:`r2dbc-postgresql`

### What were you attempting to do?

I attempt to build a native Docker image using Packeto (that uses GraalVM) using the following command:

```
./mvnw.cmd spring-boot:build-image -DskipTests
```

### What did you expect to happen?

I expect the image is built with no error.

### What was the actual behavior? Please provide log output, if possible.

Here is a full log output: [log.txt](https://github.com/paketo-buildpacks/native-image/files/7534758/log.txt)

The image cannot be built and the following error is displayed:

```
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:174]    classlist:   6,368.93 ms,  0.96 GB
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:174]        (cap):   2,071.22 ms,  0.96 GB
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:174]        setup:   6,094.75 ms,  0.96 GB
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:174]     analysis:  10,400.77 ms,  1.68 GB
[INFO]     [creator]     Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.beans.BeanUtils.instantiateClass(java.lang.Class)
[INFO]     [creator]     Parsing context:
[INFO]     [creator]        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:141)
[INFO]     [creator]        at org.springframework.boot.context.properties.bind.JavaBeanBinder.create(JavaBeanBinder.java:67)
[INFO]     [creator]        at org.springframework.boot.context.properties.bind.Binder.create(Binder.java:366)
```
...
```
[INFO]     [creator]     Caused by: com.oracle.graal.pointsto.util.AnalysisError: parsing had failed in another thread
[INFO]     [creator]            at com.oracle.graal.pointsto.util.AnalysisError.shouldNotReachHere(AnalysisError.java:153)
[INFO]     [creator]            at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:656)
[INFO]     [creator]            at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:182)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1120)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1103)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:961)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:915)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:791)
[INFO]     [creator]            at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:242)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:532)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:787)
[INFO]     [creator]            at com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:99)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:171)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:321)
[INFO]     [creator]            at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:293)
[INFO]     [creator]            ... 12 more
[INFO]     [creator]     Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.springframework.beans.BeanUtils$Kot
linDelegate.instantiateClass(java.lang.reflect.Constructor, java.lang.Object[]). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
[INFO]     [creator]            at parsing org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:196)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2624)
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:107)
```
...
```
[INFO]     [creator]     Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(java.lang.reflect.Constructor, ja
va.lang.Object[]). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:307)
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:298)
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:252)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1677)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1652)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5419)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3477)
[INFO]     [creator]            ... 39 more
```

I assume there is something wrong with `native-image` buildpack since the following lines can be found in the log:

```
[INFO]     [creator]     # Printing build artifacts to: /layers/paketo-buildpacks_native-image/native-image/sandbox.Application.build_artifacts.txt
[INFO]     [creator]     Error: Image build request failed with exit status 1
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1
```

## Build Configuration

I use `paketobuildpacks` (I have no idea what should be specified as a "platform") and here is the full build configuration: 

```
<build>
	<finalName>spring-boot-reactive</finalName>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<image>
					<builder>paketobuildpacks/builder:tiny</builder>
					<env>
						<BP_BOOT_NATIVE_IMAGE>1</BP_BOOT_NATIVE_IMAGE>
						<BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>-Dspring.spel.ignore=true</BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
					</env>
					<buildpacks>
						<buildpack>gcr.io/paketo-buildpacks/java-native-image:5.12.0</buildpack>
					</buildpacks>
				</image>
			</configuration>
		</plugin>

	</plugins>
</build>
```

### What buildpacks are you using? Please include versions.
I use `java-native-image` of version `5.12.0` as long as it is compatible with GraalVM supporting Java 17.

### What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

I use `paketobuildpacks/builder:tiny` as shown in the configuration above.

### Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

I have no other configuration.

_____________

**A side question:** Does exist a compatibility matrix between Java version, GraalVM version, individual paketo-buildpacks? How is [bellsoft-liberica](https://github.com/paketo-buildpacks/bellsoft-liberica/releases/tag/v8.9.0) relevant to them?

**Comment by dmikusa-pivotal** [comment]
Native compilation issues are not typically buildpack problems. The buildpack is only responsible for installing and running the `native-image` tool with some default options that a user can override. 

If a compilation problem occurs, it's typically something with the application's code or dependencies. 

There are a couple of good sanity checks you can run to help narrow down where the problem exists:

1. Strip out as much as possible from your application or download a minimal base app from https://start.spring.io and build that. If that works correctly, the problem lies somewhere in the code or dependencies that you've added.

2. Use [the instructions here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-build-tools) to build. This does require you to install the native image tools on your machine, so make sure you are installing the exact same versions as being installed by the buildpack. Then build and see if the build works. If this build works, but buildpacks do not, then see if you can put together a reproduction app you can share. I'd be happy to take a look and see what is going on.

Final note. You didn't mention the version of Spring Native that you're using but my understanding is that Spring Native 0.10.x does not support Java 17, but that the next release should.

**Comment by Nikolas-Charalambidis** [comment]
Thanks for the quick reaction. Yes, I used Spring Native version of `0.10.0` but also `0.11.0-M1` - it results in the very same error. I try to create a task on their repository.

**Comment by dmikusa-pivotal** [comment]
OK, I'm going to close out this issue. If it turns out to be something buildpack related, feel free to reopen this.
