### ISSUE TITLE
Ignoring locale settings and sun.jnu.encoding

### ISSUE THREAD

**Issue by Schaka** [paketo-buildpacks/native-image#344]
I hope I'm in the right place and this isn't directly related to GraalVM. So please excuse me if I'm wasting yourn time.
You can find all the code I'm talking about right here: https://github.com/Schaka/janitorr/tree/bazarr-support

The image is built using the Spring-Boot bootImage step via Gradle and I'm passing these ENV variables.

```
"BPE_DEFAULT_LANG" to "en_US.UTF-8",
"BPE_LANG" to "en_US.UTF-8",
"BPE_LC_ALL" to "en_US.UTF-8",
"JAVA_TOOL_OPTIONS" to """
    -Dsun.jnu.encoding=UTF-8
    -Dfile.encoding=UTF-8
""".trimIndent(),
"BP_NATIVE_IMAGE_BUILD_ARGUMENTS" to """
    -march=compatibility
    -H:+AddAllCharsets
    -Dsun.jnu.encoding=UTF-8
    -Dfile.encoding=UTF-8
""".trimIndent()
```

My host (Debian 12) has LANG set correctly and LC_ALL not set at all.
[According to the docs](https://paketo.io/docs/howto/configuration/#configuring-locale), I also passed these arguments to Docker via compose.yml

According to the docs, this would not print correctly to console (docker logs) otherwise, but definitely seems to. Granted, I use logback and not any direct prints, so there is a chance this fixes things magically.
```
services:
  janitorr:
    container_name: janitorr
    image: ghcr.io/schaka/janitorr:native-amd64-80-merge
    user: 1000:1000
    ports:
      - 8978:8978 # Technically, we don't publish any endpoints, so this isn't strictly required
    volumes:
      - /appdata/janitorr/config/application.yml:/workspace/application.yml
      - /share_media:/data
    environment:
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
```

Yet, the second I use Path.of("a path with an ümläüt"), I run into the following exception:

```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /data/media/anime-movies/Nausicaä of the Valley of the Wind (1984) [imdbid-tt0087544]/Nausicaä of the Valley of the Wind (1984) [imdbid-tt0087544] - [Bluray-1080p][FLAC 2.0][x264].mkv
	at java.base@23/sun.nio.fs.UnixPath.encode(UnixPath.java:131) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
	at java.base@23/sun.nio.fs.UnixPath.<init>(UnixPath.java:77) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
	at java.base@23/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:312) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
	at java.base@23/java.nio.file.Path.of(Path.java:148) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
	at com.github.schaka.janitorr.mediaserver.AbstractMediaServerService.pathStructure$janitorr(AbstractMediaServerService.kt:71) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
	at com.github.schaka.janitorr.mediaserver.AbstractMediaServerService.createLinks(AbstractMediaServerService.kt:99) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
```

Is there something I'm missing here, or could this be a bug in GraalVM somehow?
Looking at the code, UnixFileSystem definitely reads `sun.jnu.encoding`. The filepath is received as a valid UTF-8 string via REST.

**Comment by dmikusa** [comment]
Did you try with `-J` flag to `native-image`?

>    -J<flag>              pass <flag> directly to the JVM running the image generator

So if you're setting additional args like ...

>"BP_NATIVE_IMAGE_BUILD_ARGUMENTS" to """
>    -march=compatibility
>    -H:+AddAllCharsets
>    -Dsun.jnu.encoding=UTF-8
>    -Dfile.encoding=UTF-8

Then try `-J-Dsun.jnu.encoding=UTF-8` and `-J-Dfile.encoding=UTF-8`. That should pass those args through to the build time. I see some evidence of that helping similar issues [here](https://github.com/oracle/graal/issues/2492#issuecomment-654513764). 

In general, what I suggest with something like this is to get it working without buildpacks. So make it build and work when calling `native-image` directly (or with their gradle tools) on your machine. When it's working well that way, look at the flags you had to pass to native-image and then update `BP_NATIVE_IMAGE_BUILD_ARGUMENTS` according.

The buildpack is just installing & running `native-image` for you. It attempts to add some basic arguments that you'll need, but beyond that, it's up to you to pass additional arguments through.

**Comment by Schaka** [comment]
I did test it without buildpacks about an hour ago and made a small sample project.
I was about to update the issue and figured it may be buildpack related.
I've also considered it may be a problem with Adoptium or Bellsoft.

Here's a small test project:
[graalvm-test.zip](https://github.com/user-attachments/files/17367340/graalvm-test.zip)

If you replace the base image in the Dockerfile with 21 instead of 23, you can start it with any combination of parameters. They end up not mattering and you always get the same error. With 23 it just works and you don't have to set encoding parameters at all.


I'll give the `-J` flag a try. I've managed to get `-Dsun.jnu.encoding=UTF-8" and read it from within the image as such by adjusting the CMD (according to docs) but the actual value seemed to get completely ignored.

**Comment by dmikusa** [comment]
This doesn't seem like something that's specific to buildpacks, if I'm following your tests here. If you can reproduce it using the standard Dockerfiles, that's a behavior with native-image itself.

All I can suggest is that we do have Java 23 available in buildpacks, https://github.com/paketo-buildpacks/bellsoft-liberica/releases/tag/v10.9.0, has it Java 23, and that was pulled into https://github.com/paketo-buildpacks/java/releases/tag/v16.1.0 last week's release. So if using Java 23 works with your Dockerfile sample, I'd bet it works with buildpacks too.

**Comment by Schaka** [comment]
So I had already been using Java 23 for a while. 
This is my log output in that regard:
```
$JAVA_TOOL_OPTIONS                                                                        the JVM launch flags
    [creator]         Using Java version 23 from BP_JVM_VERSION
    [creator]       BellSoft Liberica NIK 23.0.0: Contributing to layer
```

I now added `"paketobuildpacks/oracle"`. I was hoping there was a way to use Oracle's GraalVM as a base image directly and this seems to be it. 

Unfortunately, the result is still the same. The resulting image cannot use `Path.of("/umläut")` without an exception being thrown. 

If I can recreate it in a sample project specifically built around paketo's buildpacks, will you look into it?

**Comment by dmikusa** [comment]
What we'd need to look into this is something like your sample project from before that works when you build with a Dockerfile or just on the local machine, but does not work when building the same source code with buildpacks. If you have a sample like that, I can take a look.

**Comment by Schaka** [comment]
[native-image-error.zip](https://github.com/user-attachments/files/17368251/native-image-error.zip)

If you do `gradle bootBuildImage` and `docker run native-image-error`, you'll see the error.
It will not error if you just run it locally, only in the image produced by buildpacks.

You can even try `docker run native-image-error -Dsun.jnu.encoding=UTF-8`.
I think it's some form of base image that doesn't accept or delegate the `LANG` or `LC_ALL` env variables or the base image is one where GraalVM doesn't interpret them correctly at build time.

As you can see in my previous example, it works just fine using Oracle's base image with `javac` and `native-image`. I'm at a bit of a loss trying to figure out what's different. 

You guys do amazing work, so I wouldn't be surprised if I fucked up somehow.

**Comment by dmikusa** [comment]
A couple of observations...

- ghcr.io/graalvm/graalvm-community:21 doesn't seem to have locales installed correctly, bash in that image can't even display a filename with an umlaut correctly. Conversely ghcr.io/graalvm/graalvm-community:23 does and bash works correctly there. I don't think this is a difference in native-image, just the container image.

- https://github.com/oracle/graal/issues/9504 so `JAVA_TOOL_OPTIONS` won't work when you run your image, a native image binary doesn't look at this env variable. A native-image binary does support reading system properties from arguments to the application though, so that's why it picks them up when you run your application image passing the system props as args to the binary.

- As far as I can tell the Paketo base/run images have locale set up correctly. At least with the base & full images, I can exec into the container, run `locale` and see that it's reporting `en_US.UTF-8`. I can use UTF-8 codes in file names with bash and everything seems to work OK there. It also has been reported to work with a JVM and other language runtimes. It is just with the native-image app where I have trouble with `Path.of`. If we are missing a package to make this work, let me know and we can look at adding it. I would just need to know the Ubuntu package to install (or possibly more details on what GraalVM needs, and I could try to find out what Ubuntu package provides that).

- I tried with Oracle GraalVM 21 & 23. Same results. No difference there.

**Comment by Schaka** [comment]
I've also created an issue [over at at GraalVM](https://github.com/oracle/graal/issues/9879). The package they use seems to be `glibc-all-langpacks`.

I can't find the Ubuntu/Debian equivalent. Maybe they can shine a light on it.

The `locales` package is available on Ubuntu 22, but that should be installed by default.

Having a quick look, at most I can tell that Oracle Linux 9 supplies glibc-all-langpacks 2.34, whereas Ubuntu's locale uses 2.35. Hopefully that one minor version isn't what breaks it here.

**Comment by Schaka** [comment]
I ended up using `--patch-module`. Recompiling the `sun.nio.fs.Util` class myself with UTF-8 forced, doing a hacky copying into a folder structure that's accepted by the compiler and it got accepted by the native image without issue.
[native-image-error.zip](https://github.com/user-attachments/files/17439464/native-image-error.zip)

It's incredibly hacky but may solve this for anyone else that needs a temporary (haha) solution.
The real problem still needs fixing but I suspect it'll be a while before the GraalVM team gives a definitive answer as to what it actually required and the system property is set under the hood.

**Comment by dmikusa** [comment]
Thanks for sharing! I'm subscribed on the GraalVM issue, so I'll keep an eye on what they say and if there's anything we can do to make this just work, I'll open up issues.

**Comment by wertecs** [comment]
I've recently stumbled across this problem as well.

I've solved it with 

```
            // Set system locale for UTF-8 support
            'BPE_LANG'      : 'en_US.UTF-8',
            'BPE_LC_ALL'    : 'en_US.UTF-8',
            'BPE_LC_CTYPE'  : 'en_US.UTF-8',
```

In combination with `builder = "paketobuildpacks/builder-jammy-base"`

Looks like the current default build image for springboot `builder-noble-java-tiny` but `builder-jammy-java-tiny` as well, so maybe all `java-tiny` images do not support of setting the locale

The value for `sun.jnu.encoding` was `ANSI_X3.4-1968` no matter what I did, until I changed the builder image

**Comment by Schaka** [comment]
Maybe this could be documented?
I just ran into it with a non-native image build as well.

Even passing `-Dsun.jnu.encoding=UTF-8` directly to `JAVA_TOOL_OPTIONS`, it gets ignored completely. 
The only options around it are either patching one of the modules via `JAVA_TOOL_OPTIONS`  when starting the VM (and ideally, we don't wanna patch in classes) or using the base builder.

Or maybe add the locale component? As far as I understand, these are Ubuntu images. `locales` for `locale-gen` and `update-locale` should be included.

**Comment by Schaka** [comment]
> [@Schaka](https://github.com/Schaka) - I just recently documented this, so hopefully that helps with awareness, see https://paketo.io/docs/howto/configuration/#locale-caveats

Thank you!

> > The only options around it are either patching the java.base via JAVA_TOOL_OPTIONS when starting the VM (and ideally, we don't wanna patch in classes)
For native image, I found that this approach wasn't necessary. If `LC_ALL` is set to `en_US.UTF-8` at the time that `native-image` is called to compile, it will automatically transfer to the binary and whatever you choose to supply at runtime of native executable is then ignored. I can't say if that's intended behavior, but it seems to be.

Luckily for us at least, that just means the correct locale information needs to be passed at build time.

> Can you expand on this solution? Just curious if there's something the buildpacks could do here to perhaps make this work for Java apps, but without the OS level packages.

I'm not sure this is a workable solution at all, but I'll try to go into some detail anyway.
You can take a look at [this commit where I originally implemented](https://github.com/Schaka/janitorr/commit/f985465aadcf7c308aa86909e7239bc54602cea5) it after opening this issue.

If you look at the original source, you can find what I changed here:
```
https://code.googlesource.com/edge/openjdk/+/jdk8u111-b09/jdk/src/share/classes/sun/nio/fs/Util.java?autodive=0%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F
```

It could be possible to manually read `LC_CTYPE` or `LC_ALL` at build time, recompile that class and then pass
`--patch-module=java.base=/path/to/java.base` to the JVM when running it. Keep in mind, you would need the JDK to compile `java.nio.fs.Util` because it depends on other classes of the JDK. You don't need to recompile the entire module, just that class. If you then patch that module and the only difference is that class, it gets picked up as if it was the original one.

This is similar to how in earlier versions of Java, you could just create the same package as one of your dependencies (or the JDK) and compile your own class as part of your project, which would be prioritized by the ClassLoader at runtime over the library.

I hope this helps, but I'm not confident this is a great solution for something you want ship as a minimal buildpack.
